name: stcerwallet
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+4

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  provider: ^3.1.0+1
  qr_flutter: ^3.2.0
  bip39: ^1.0.3
  tweetnacl: ^0.3.1
  pointycastle: ^1.0.0
  hex: ^0.1.2
  shared_preferences: ^0.5.6+1
  camera: ^0.5.8+7
  firebase_ml_vision: 0.9.3+5
  web_socket_channel: ^1.1.0
  intl: ^0.16.1
  flutter_spinkit: "^4.1.1+1"
  #firebase_analytics: ^5.0.11
  url_launcher: ^5.4.1
  flutter_hooks: ^0.9.0
  built_value: ^7.1.0
  built_collection: ^4.3.2
  flutter_redux: ^0.5.2
  font_awesome_flutter: ^8.2.0
  web3dart: ^1.2.3
  optional: '5.0.0'
  webview_flutter: 1.0.7
  sqflite: ^1.3.0
  path: 1.8.0-nullsafety.3
  flutter_slidable: 0.5.7
  starcoin_wallet:
    #git:
    #  url: git://github.com/starcoinorg/starcoin.dart
    path: /Users/fanngyuan/Documents/workspace/starcoin_wallet.dart

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  json_serializable: ^3.2.5
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - TargaryenCoin.json

    # images
    - assets/images/ic_logo.png
    - assets/images/ic_default_user_avatar.png
    - assets/images/ic_default_wallet_avatar_0.png
    - assets/images/ic_default_wallet_avatar_1.png
    - assets/images/ic_default_wallet_avatar_2.png
    - assets/images/ic_default_wallet_avatar_3.png
    - assets/images/ic_default_wallet_avatar_4.png
    - assets/images/ic_default_wallet_avatar_5.png
    - assets/images/ic_default_wallet_avatar_6.png
    - assets/images/ic_default_wallet_avatar_7.png
    - assets/images/ic_default_wallet_avatar_8.png
    - assets/images/ic_default_wallet_avatar_9.png
    - assets/images/ic_default_wallet_avatar_10.png
    - assets/images/ic_gas_price_fast.png
    - assets/images/ic_gas_price_slow.png
    - assets/images/ic_qrcode_scan.png
    - assets/images/ic_qrcode.png
    - assets/images/ic_transfer_arp_b.png
    - assets/images/ic_transfer_bat_b.png
    - assets/images/ic_transfer_bnt_b.png
    - assets/images/ic_transfer_eos_b.png
    - assets/images/ic_transfer_eth_b.png
    - assets/images/ic_transfer_every_b.png
    - assets/images/ic_transfer_iost_b.png
    - assets/images/ic_transfer_knc_b.png
    - assets/images/ic_transfer_lrc_b.png
    - assets/images/ic_transfer_rdn_b.png
    - assets/images/ic_transfer_req_b.png
    - assets/images/ic_transfer_rhoc_b.png
    - assets/images/ic_transfer_vite_b.png
    - assets/images/ic_transfer_weth_b.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
